<a href="https://colab.research.google.com/github/CharlyPierce/Basico/blob/main/MSE_sparse_matrx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
tf.gather_nd(
    indices = [[1]],
    params = [[['a0', 'b0'], ['c0', 'd0']],
              [['a1', 'b1'], ['c1', 'd1']]]).numpy()

array([[[b'a1', b'b1'],
        [b'c1', b'd1']]], dtype=object)

In [ ]:
from urllib.request import urlretrieve
import zipfile
urlretrieve("https://files.grouplens.org/datasets/movielens/ml-100k.zip", "movielens.zip")
#DEscara archivos con nombre movielens.zip
zip_ref = zipfile.ZipFile('movielens.zip', "r")#Lee lo que esta en movielens.zip
zip_ref.extractall()#extrae el contenido de movielens.ziip
users_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv('ml-100k/u.user', sep='|', names=users_cols, encoding='latin-1')
ratings_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=ratings_cols, encoding='latin-1')
genre_cols = [
    "genre_unknown", "Action", "Adventure", "Animation", "Children", "Comedy",
    "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror",
    "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"
]
movies_cols = [
    'movie_id', 'title', 'release_date', "video_release_date", "imdb_url"
] + genre_cols
movies = pd.read_csv('ml-100k/u.item', sep='|', names=movies_cols, encoding='latin-1')
users["user_id"] = users["user_id"].apply(lambda x: str(x-1))
movies["movie_id"] = movies["movie_id"].apply(lambda x: str(x-1))
movies["year"] = movies['release_date'].apply(lambda x: str(x).split('-')[-1])
#El menos 1 es para solo seleccionar el año
ratings["movie_id"] = ratings["movie_id"].apply(lambda x: str(x-1))
ratings["user_id"] = ratings["user_id"].apply(lambda x: str(x-1))
ratings["rating"] = ratings["rating"].apply(lambda x: float(x))
genre_occurences = movies[genre_cols].sum().to_dict()

In [ ]:
  indices = ratings_df[['user_id', 'movie_id']].values
  values = ratings_df['rating'].values
  return tf.SparseTensor(
      indices=indices,
      values=values,
      dense_shape=[users.shape[0], movies.shape[0]])

In [ ]:
ratings['user_id']=pd.to_numeric(ratings['user_id'],errors='coerce')
ratings['movie_id']=pd.to_numeric(ratings['movie_id'],errors='coerce')

indi=ratings[['user_id','movie_id']].values
valu=ratings['rating'].values
dens=[users.shape[0], movies.shape[0]]

In [ ]:
a=tf.SparseTensor(indices=[[0, 0],[1, 2]], values=[1, 2], dense_shape=[3, 4])
print(tf.sparse.to_dense(a))#El error se genera porque los indices no estan
#ordenados. Debes ordenar los indices para que no se produsca este error

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
tf.sparse.reorder(a)#Corrige el problema de ordenamiento de indices

In [ ]:
a=tf.SparseTensor(indices=[[1, 2], [0, 0]], values=[1, 2], dense_shape=[3, 4])
a=tf.sparse.reorder(a)#corrige el proble de ordenamiento de indices
print(tf.sparse.to_dense(a))#El error se genera porque los indices no estan
#ordenados. Debes ordenar los indices para que no se produsca este error

tf.Tensor(
[[2 0 0 0]
 [0 0 1 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
b1=tf.SparseTensor(indices=indi,values=valu,dense_shape=dens)
b2=tf.sparse.reorder(b1)
b=tf.sparse.to_dense(b2)
print(b)

tf.Tensor(
[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]], shape=(943, 1682), dtype=float64)


In [ ]:
b1.values,b2.values#b1 valores sin ordenar#b2valores ordenados

(<tf.Tensor: shape=(100000,), dtype=float64, numpy=array([3., 3., 1., ..., 1., 2., 3.])>,
 <tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>)

In [ ]:
tf.sparse.reorder(b1).indices,tf.sparse.reorder(b1).values

(<tf.Tensor: shape=(100000, 2), dtype=int64, numpy=
 array([[   0,    0],
        [   0,    1],
        [   0,    2],
        ...,
        [ 942, 1187],
        [ 942, 1227],
        [ 942, 1329]])>,
 <tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>)

In [ ]:
asr=ratings[['user_id','movie_id']].values
asr#indices noo ordenados b2.indices #indices ordenados

array([[ 195,  241],
       [ 185,  301],
       [  21,  376],
       ...,
       [ 275, 1089],
       [  12,  224],
       [  11,  202]])

In [ ]:
tf.gather_nd(b,b2.indices)#b hace funcion de 
#tf.matmul(user_embeddings, movie_embeddings, transpose_b=True)

<tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>

In [ ]:
b2.values,prediccion

(<tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>,
 <tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>)

In [ ]:
prediccion=tf.gather_nd(b,b2.indices)#como ve es la aproximacion a la matriz sparse
#entonces obtenemos los mismos indices que la matriz sparse para comarar
#En la linea siguiente deberia calcular el error cuadrado entre la  prediccion y 
#la matriz de aprocimacion b juga el papel de U*V.T = <U*V>

In [ ]:
b

<tf.Tensor: shape=(943, 1682), dtype=float64, numpy=
array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])>

In [ ]:
prediccion

<tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>

In [ ]:
b1.values#valores sin ordenar

<tf.Tensor: shape=(100000,), dtype=float64, numpy=array([3., 3., 1., ..., 1., 2., 3.])>

In [ ]:
b2.values#valores ordenados

<tf.Tensor: shape=(100000,), dtype=float64, numpy=array([5., 3., 4., ..., 3., 3., 3.])>

In [ ]:
tf.losses.mean_squared_error(b2.values,prediccion)
#b debe ser el tensor con las entradas, no la matriz sparse, tiene sentido porq tratar la
# matriz sparse seria incontables operaciones de ceros lo que no es eficiente por tanto
#b no puede ser la matriz sparse debe ser el tensor de entradas 
# b1=tf.SparseTensor(indices=indi,values=valu,dense_shape=dens)
# b2=tf.sparse.reorder(b1)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [ ]:
#title Solution#al hacer el matmul de user y movier debe salir la matrix sparse
def sparse_mean_square_error(sparse_ratings, user_embeddings, movie_embeddings):
  predictions = tf.gather_nd(
      tf.matmul(user_embeddings, movie_embeddings, transpose_b=True),
      sparse_ratings.indices)#busca los indices en la aproximacion
  loss = tf.losses.mean_squared_error(sparse_ratings.values, predictions)
  return loss

In [ ]:
ratings.head(1)#DataFrame cargado

user_id  movie_id  rating  unix_timestamp
0      195       241     3.0       881250949

In [ ]:
ratings['user_id']=pd.to_numeric(ratings['user_id'],errors='coerce')
ratings['movie_id']=pd.to_numeric(ratings['movie_id'],errors='coerce')

indi=ratings[['user_id','movie_id']].values
valu=ratings['rating'].values
dens=[users.shape[0], movies.shape[0]]#cantidad de usuarios y peliculas
a1=tf.SparseTensor(indices=indi, values=valu, dense_shape=dens)
#a1 Nuestra matriz de calificaciones con indices y los valores
a2=tf.sparse.reorder(a1)#reordenamos para visualizacion
a3=tf.sparse.to_dense(a2)#este se ocupa como matriz de aproximacion
print(a3)#"a3 la usamos como tf.matmul(user_embeddings, movie_embeddings, transpose_b=True),""

tf.Tensor(
[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]], shape=(943, 1682), dtype=float64)


In [ ]:
i1=sorted(indi,key=lambda x: x[1])#ordena en el indice 1 (521,216)
i2=sorted(i1,key=lambda x: x[0])#ordena en el indice 0 (21,56)
i3=tf.constant(i2,dtype=tf.int32)#convierte a tensor

In [ ]:
#prediccion con indices no ordenados
prediccion=tf.gather_nd(a3,indi)#En la matriz de aproximacion a3
#buscamos los mismos indices de la sparse "a1" para comparar el erro
pred2=tf.gather_nd(a3,i3)#prediccion con indices ordenados

In [ ]:
tf.losses.mean_squared_error(a1.values,prediccion)
#a1 no tiene los indices acomodados por tanto tampoco los valores
#en prediccion tambien buscamos los indices de forma no ordenada pero igual q a1
#puedes ordenar indices que ordenara valores en a1 lo guardamos en arriba en "a2"
#pero tambien debes buscarlos ordenadamente en prediccion

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [ ]:
tf.losses.mean_squared_error(a2.values,prediccion)
#nos da un error distinto de cero porque compara el indice [195,241] de prediccion con el [0,0] de a2
#y asi como no estan ordenados da diferente de cero

<tf.Tensor: shape=(), dtype=float64, numpy=2.51602>

In [ ]:
tf.losses.mean_squared_error(a2.values,pred2)
#Compara los indices ordenados, en a2 ordenamos indices y en pred2 buscamos los indices ordenados
#El orden que que tienes los indices es el orden en q tendras los valores de las entradas, por eso
#es importante tener bien ordenados los indices para que no de ningun problema

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [ ]:
U = tf.Variable(tf.random_normal([50, 3], stddev=1))

V = tf.Variable(tf.random_normal([30, 3], stddev=1))

In [ ]:
tf.Variable(tf.random.normal([2,3],stddev=25,mean=115))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[149.76897, 130.11696, 128.727  ],
       [112.11168, 137.47949, 140.19308]], dtype=float32)>